modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
config="maidhome_bridge.mixins.json"

[[mods]]
modId="maidhome_bridge"
version="${version}"
displayName="MaidHome Bridge"
authors="JumDa5he"
description='''Minecraft 与 Unity MaidHome 之间的女仆档案、模型、音效和房屋传输。'''

[[dependencies.maidhome_bridge]]
modId="neoforge"
type="required"
versionRange="[21.1.1,21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.maidhome_bridge]]
modId="maid_file_manager"
type="required"
versionRange="[1.4.2,1.5)"
ordering="AFTER"
side="BOTH"
[[dependencies.maidhome_bridge]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.maidhome_bridge]]
modId="touhou_little_maid"
type="required"
versionRange="[1.5.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.maidhome_bridge]]
modId="minetomesh"
type="optional"
versionRange="[1.2.0,1.3)"
ordering="AFTER"
side="CLIENT"
